server:
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/app
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      max-request-size: 10485760
      max-file-size: 10485760
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:/mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8989/eureka,http://localhost:8985/eureka
  instance:
    prefer-ip-address: true
